sonar.projectKey=PoweredBySymfony_wine-cellar_a3469480-cb67-45ab-92f1-9cc84af31788
sonar.projectName=Wine Cellar
sonar.sourceEncoding=UTF-8

sonar.sources=wine_cellar
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=wine_cellar/**/migrations/**,wine_cellar/static/**,wine_cellar/assets/js/*.map
sonar.coverage.exclusions=wine_cellar/conf/**,wine_cellar/**/admin.py,wine_cellar/**/apps.py,wine_cellar/**/migrations/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
